import path from 'node:path'
import { fileURLToPath } from 'node:url'
import js from '@eslint/js'
import { FlatCompat } from '@eslint/eslintrc'
import tseslint from 'typescript-eslint'
import prettier from 'eslint-config-prettier'

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const compat = new FlatCompat({ baseDirectory: __dirname })

export default tseslint.config(
  {
    ignores: [
      '**/node_modules/**',
      '**/.next/**',
      '**/.turbo/**',
      '**/dist/**',
      '**/coverage/**',
      'packages/db/generated/**',
      // Generated by `next build` / `next dev`; Next.js owns it, we never edit it.
      '**/next-env.d.ts',
      // Playwright output: reports, traces, and saved session cookies.
      'e2e/.auth/**',
      'e2e/playwright-report/**',
      'e2e/test-results/**',
      'e2e/blob-report/**',
    ],
  },
  js.configs.recommended,
  ...tseslint.configs.recommended,
  ...compat.extends('next/core-web-vitals'),
  {
    settings: {
      next: { rootDir: ['apps/*/'] },
    },
    rules: {
      '@typescript-eslint/no-unused-vars': [
        'error',
        { argsIgnorePattern: '^_', varsIgnorePattern: '^_', caughtErrorsIgnorePattern: '^_' },
      ],
      '@typescript-eslint/no-explicit-any': 'warn',
      'no-console': ['warn', { allow: ['warn', 'error', 'info'] }],
    },
  },
  {
    files: ['**/*.mjs', '**/*.cjs', 'scripts/**/*.mjs', 'packages/db/prisma/seed.ts'],
    rules: {
      'no-console': 'off',
    },
  },
  prettier,
)
